apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user-tls
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  # No authorization section - user has full access to all topics/groups
  # Use with clusters that have authentication but NO authorization configured
