apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: compacted-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 3
  config:
    cleanup.policy: compact
    min.cleanable.dirty.ratio: 0.5
    delete.retention.ms: 86400000  # 1 day
    segment.ms: 3600000  # 1 hour
    compression.type: snappy
