apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: multi-partition-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000  # 7 days
    segment.bytes: 1073741824  # 1 GB
    compression.type: producer
    min.insync.replicas: 2
