apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: consumer-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Read from topics with prefix
      - resource:
          type: topic
          name: app-
          patternType: prefix
        operations:
          - Read
          - Describe
        host: "*"
      # Consumer group access
      - resource:
          type: group
          name: app-consumer-group
          patternType: literal
        operations:
          - Read
        host: "*"
